@host = http://test.ahdis.ch/matchbox/fhir

### Create modular questionnaire with $assemble operation
### first upload also ch-orf-module-*.json Questionnaires i ch-orf assemble.http

GET {{host}}/Questionnaire HTTP/1.1
Accept: application/json+fhir

###
POST {{host}}/Questionnaire HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./output/Questionnaire-ch-etoc-module-purpose.json


###
POST {{host}}/Questionnaire HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./output/Questionnaire-ch-etoc-module-diagnosis.json

###
POST {{host}}/Questionnaire HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./output/Questionnaire-ch-etoc-module-anamnesis.json

###
POST {{host}}/Questionnaire HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./output/Questionnaire-ch-etoc-module-medication.json

###
POST {{host}}/Questionnaire HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./output/Questionnaire-ch-etoc-module-allergyintolerance.json

###
POST {{host}}/Questionnaire HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./output/Questionnaire-ch-etoc-module-immunizationstatus.json

###
POST {{host}}/Questionnaire HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./output/Questionnaire-ch-etoc-module-lab.json

###
POST {{host}}/Questionnaire HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./output/Questionnaire-ch-etoc-module-pathology.json

###
POST {{host}}/Questionnaire HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./output/Questionnaire-ch-etoc-module-imaging.json

###
POST {{host}}/Questionnaire HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./output/Questionnaire-ch-etoc-module-cardiology.json

###
POST {{host}}/Questionnaire HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./output/Questionnaire-ch-etoc-module-attachment.json

### $assemble operation on modular Questionnaire
POST {{host}}/Questionnaire/$assemble HTTP/1.1
Accept: application/json+fhir
Content-Type: application/json+fhir

< ./output/Questionnaire-QuestionnaireEtoc-modular.json

